apiVersion: v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-web
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.ci_env.url }}
    http:
      paths:
        - backend:
            serviceName: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-web
            servicePort: 80
          path: /