apiVersion: apps/v1beta1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-rabbit
  labels:
    app: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-rabbit
    version: {{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  ports:
  - name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-rabbit
    port: 5672
  selector:
    app: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-rabbit

