apiVersion: apps/v1beta1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-web
  labels:
    app: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-web
    version: {{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP

  selector:
    app: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-web
  type: NodePort
